name: Java CI with Gradle, Build and Push Docker Image

on:
  push:
    branches: [ "Provider" ]
  pull_request:
    branches: [ "Provider" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean :launchers:ids-connector:build
          
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build & push Docker image  
      uses: docker/build-push-action@v4
      with:
        file: launchers/ids-connector/Dockerfile
        context: . 
        push: true
        tags: djeutchou/edc-ids-connector:latest

      
  
